### ISSUE TITLE
[interaction::commandInteractionAutocomplete] DiscordAPIError: Invalid Form Body
data.choices[0].value: Choice values must be of type "integer"
data.choices[1].value: Choice values must be of type "integer"
data.choices[2].value: Choice values must be of t

### ISSUE THREAD

**Issue by HealthScreeningBot-Github** [HealthScreening/HealthScreeningBot#260]
# Error Details
- Error Type: **interaction::commandInteractionAutocomplete**
- Error Name: **DiscordAPIError**
- Error Message: **Invalid Form Body
data.choices[0].value: Choice values must be of type "integer"
data.choices[1].value: Choice values must be of type "integer"
data.choices[2].value: Choice values must be of type "integer"
data.choices[3].value: Choice values must be of type "integer"
data.choices[4].value: Choice values must be of type "integer"
data.choices[5].value: Choice values must be of type "integer"
data.choices[6].value: Choice values must be of type "integer"
data.choices[7].value: Choice values must be of type "integer"
data.choices[8].value: Choice values must be of type "integer"
data.choices[9].value: Choice values must be of type "integer"
data.choices[10].value: Choice values must be of type "integer"
data.choices[11].value: Choice values must be of type "integer"
data.choices[12].value: Choice values must be of type "integer"
data.choices[13].value: Choice values must be of type "integer"
data.choices[14].value: Choice values must be of type "integer"
data.choices[15].value: Choice values must be of type "integer"
data.choices[16].value: Choice values must be of type "integer"
data.choices[17].value: Choice values must be of type "integer"
data.choices[18].value: Choice values must be of type "integer"
data.choices[19].value: Choice values must be of type "integer"
data.choices[20].value: Choice values must be of type "integer"
data.choices[21].value: Choice values must be of type "integer"
data.choices[22].value: Choice values must be of type "integer"
data.choices[23].value: Choice values must be of type "integer"
data.choices[24].value: Choice values must be of type "integer"**
- Error Occured At: **Friday, December 24, 2021, 11:51:45 PM Eastern Standard Time**

## Error Stack Trace

```
DiscordAPIError: Invalid Form Body
data.choices[0].value: Choice values must be of type "integer"
data.choices[1].value: Choice values must be of type "integer"
data.choices[2].value: Choice values must be of type "integer"
data.choices[3].value: Choice values must be of type "integer"
data.choices[4].value: Choice values must be of type "integer"
data.choices[5].value: Choice values must be of type "integer"
data.choices[6].value: Choice values must be of type "integer"
data.choices[7].value: Choice values must be of type "integer"
data.choices[8].value: Choice values must be of type "integer"
data.choices[9].value: Choice values must be of type "integer"
data.choices[10].value: Choice values must be of type "integer"
data.choices[11].value: Choice values must be of type "integer"
data.choices[12].value: Choice values must be of type "integer"
data.choices[13].value: Choice values must be of type "integer"
data.choices[14].value: Choice values must be of type "integer"
data.choices[15].value: Choice values must be of type "integer"
data.choices[16].value: Choice values must be of type "integer"
data.choices[17].value: Choice values must be of type "integer"
data.choices[18].value: Choice values must be of type "integer"
data.choices[19].value: Choice values must be of type "integer"
data.choices[20].value: Choice values must be of type "integer"
data.choices[21].value: Choice values must be of type "integer"
data.choices[22].value: Choice values must be of type "integer"
data.choices[23].value: Choice values must be of type "integer"
data.choices[24].value: Choice values must be of type "integer"
    at RequestHandler.execute (/Users/aoyansarkar/WebstormProjects/HealthScreeningBot/node_modules/discord.js/src/rest/RequestHandler.js:349:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/Users/aoyansarkar/WebstormProjects/HealthScreeningBot/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at async AutocompleteInteraction.respond (/Users/aoyansarkar/WebstormProjects/HealthScreeningBot/node_modules/discord.js/src/structures/AutocompleteInteraction.js:95:5)
    at async afterTimeAutocomplete (/Users/aoyansarkar/WebstormProjects/HealthScreeningBot/src/commands/error/log/view/autocomplete/afterTime.js:41:5)
    at async commandInteractionAutocomplete (/Users/aoyansarkar/WebstormProjects/HealthScreeningBot/src/client/interactions/commandInteractionAutocomplete.js:32:17)
    at async HealthScreeningBotClient.oninteractionCreate (/Users/aoyansarkar/WebstormProjects/HealthScreeningBot/src/client/extraClient.js:125:28)
```

## Error Metadata

```json
{
    "user": "199605025914224641",
    "guild": "919616827338924042",
    "channel": "919616827338924045",
    "command": {
        "base": "error",
        "subcommand": "view",
        "subcommandGroup": "log"
    },
    "arguments": [
        {
            "name": "log",
            "type": "SUB_COMMAND_GROUP"
        }
    ]
}
```

# Issue Details
- Posted By: **@PythonCoderAS**
- Posted At: **Saturday, December 25, 2021, 12:04:34 AM Eastern Standard Time**

**Comment by PythonCoderAS** [comment]
Fixed in #261
