### ISSUE TITLE
[root] Error: ENOENT: no such file or directory, open '/Users/aoyansarkar/WebstormProjects/HealthScreeningBot/guides/whats_new_version_2_3.md'

### ISSUE THREAD

**Issue by HealthScreeningBot-Github** [HealthScreening/HealthScreeningBot#286]
# Error Details
- Error Type: **root**
- Error Name: **Error**
- Error Message: **ENOENT: no such file or directory, open '/Users/aoyansarkar/WebstormProjects/HealthScreeningBot/guides/whats_new_version_2_3.md'**
- Error Occured At: **Saturday, December 25, 2021, 9:09:57 PM Eastern Standard Time**

## Error Stack Trace

```
Error: ENOENT: no such file or directory, open '/Users/aoyansarkar/WebstormProjects/HealthScreeningBot/guides/whats_new_version_2_3.md'
```

## Error Metadata

```json
{}
```

# Issue Details
- Posted By: **@PythonCoderAS**
- Posted At: **Saturday, December 25, 2021, 9:27:48 PM Eastern Standard Time**

**Comment by PythonCoderAS** [comment]
Closed in #284
