### ISSUE TITLE
[Bug]: Bot may need to be updated due to the codebase in healthscreening changing

### ISSUE THREAD

**Issue by poopyhed444** [HealthScreening/HealthScreeningBot#424]
### Description

![1953EBAA-544B-4EF4-BB7C-161AB6D6991A](https://user-images.githubusercontent.com/85253873/147839961-0f519a85-a3dd-43d4-89dd-793de6ccea2a.jpg)

**Comment by PythonCoderAS** [comment]
It was updated to latest in #423 (for now)

**Comment by poopyhed444** [comment]
nvm
![image](https://user-images.githubusercontent.com/85253873/147893473-b70f3f46-1202-4dfc-8210-ad2f308e68f0.png)

**Comment by PythonCoderAS** [comment]
Working on it again.

**Comment by PythonCoderAS** [comment]
It was updated to latest in #432 (for now).

**Comment by PythonCoderAS** [comment]
This is actually more of a bug so I'll rename and relabel as appropriate.

**Comment by PythonCoderAS** [comment]
Seems to have settled down.
